#ifndef TSENTINELFRAME_H__
#define TSENTINELFRAME_H__

enum
{
	ID_SENTINEL_FRAME_GROUP_CORE = 1000,
	ID_SENTINEL_FRAME_ENABLED = 1001,
	ID_SENTINEL_FRAME_COMPOSITION = 1002,
	ID_SENTINEL_FRAME_SHOW_GUIDES = 1003,
	ID_SENTINEL_FRAME_SHOW_MASK = 1004,
	ID_SENTINEL_FRAME_SHOW_PLATFORM = 1005,
	ID_SENTINEL_FRAME_SHOW_HUD = 1006,
	ID_SENTINEL_FRAME_SCHEMA_VERSION = 1007,

	ID_SENTINEL_FRAME_FORMAT_BASE = 1100,
	ID_SENTINEL_FRAME_FORMAT_STRIDE = 20,

	ID_SENTINEL_FRAME_GROUP_ACTIONS = 3000,
	ID_SENTINEL_FRAME_CREATE_UPDATE_TAKES = 3001,
	ID_SENTINEL_FRAME_SET_OUTPUT = 3002,
	ID_SENTINEL_FRAME_REMOVE_STALE = 3003,
	ID_SENTINEL_FRAME_MARK_SUBJECT = 3004,
};

#endif
